/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sudoku;
import sudoku.Board;
import SudokuGenerator.GenerateRandom;

/**
 *
 * @author Ilias Kolesidis
 */
public class BoardGui extends javax.swing.JFrame {

    /**
     * Creates new form BoardGui
     */
    public BoardGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jButton2 = new javax.swing.JButton();
        label0_0 = new javax.swing.JLabel();
        label1_0 = new javax.swing.JLabel();
        label2_0 = new javax.swing.JLabel();
        label0_1 = new javax.swing.JLabel();
        label1_1 = new javax.swing.JLabel();
        label2_1 = new javax.swing.JLabel();
        label0_2 = new javax.swing.JLabel();
        label1_2 = new javax.swing.JLabel();
        label2_2 = new javax.swing.JLabel();
        label4_2 = new javax.swing.JLabel();
        label5_2 = new javax.swing.JLabel();
        label3_0 = new javax.swing.JLabel();
        label4_0 = new javax.swing.JLabel();
        label5_0 = new javax.swing.JLabel();
        label3_1 = new javax.swing.JLabel();
        label4_1 = new javax.swing.JLabel();
        label5_1 = new javax.swing.JLabel();
        label3_2 = new javax.swing.JLabel();
        label7_2 = new javax.swing.JLabel();
        label8_2 = new javax.swing.JLabel();
        label6_0 = new javax.swing.JLabel();
        label7_0 = new javax.swing.JLabel();
        label8_0 = new javax.swing.JLabel();
        label6_1 = new javax.swing.JLabel();
        label7_1 = new javax.swing.JLabel();
        label8_1 = new javax.swing.JLabel();
        label6_2 = new javax.swing.JLabel();
        label0_3 = new javax.swing.JLabel();
        label1_3 = new javax.swing.JLabel();
        label2_3 = new javax.swing.JLabel();
        label0_4 = new javax.swing.JLabel();
        label1_4 = new javax.swing.JLabel();
        label2_4 = new javax.swing.JLabel();
        label0_5 = new javax.swing.JLabel();
        label1_5 = new javax.swing.JLabel();
        label2_5 = new javax.swing.JLabel();
        label4_5 = new javax.swing.JLabel();
        label5_5 = new javax.swing.JLabel();
        label3_3 = new javax.swing.JLabel();
        label4_3 = new javax.swing.JLabel();
        label5_3 = new javax.swing.JLabel();
        label3_4 = new javax.swing.JLabel();
        label4_4 = new javax.swing.JLabel();
        label5_4 = new javax.swing.JLabel();
        label3_5 = new javax.swing.JLabel();
        label7_5 = new javax.swing.JLabel();
        label8_5 = new javax.swing.JLabel();
        label6_3 = new javax.swing.JLabel();
        label7_3 = new javax.swing.JLabel();
        label8_3 = new javax.swing.JLabel();
        label6_4 = new javax.swing.JLabel();
        label7_4 = new javax.swing.JLabel();
        label8_4 = new javax.swing.JLabel();
        label6_5 = new javax.swing.JLabel();
        label0_6 = new javax.swing.JLabel();
        label1_6 = new javax.swing.JLabel();
        label2_6 = new javax.swing.JLabel();
        label0_7 = new javax.swing.JLabel();
        label1_7 = new javax.swing.JLabel();
        label2_7 = new javax.swing.JLabel();
        label0_8 = new javax.swing.JLabel();
        label1_8 = new javax.swing.JLabel();
        label2_8 = new javax.swing.JLabel();
        label4_8 = new javax.swing.JLabel();
        label5_8 = new javax.swing.JLabel();
        label3_6 = new javax.swing.JLabel();
        label4_6 = new javax.swing.JLabel();
        label5_6 = new javax.swing.JLabel();
        label3_7 = new javax.swing.JLabel();
        label4_7 = new javax.swing.JLabel();
        label5_7 = new javax.swing.JLabel();
        label3_8 = new javax.swing.JLabel();
        label7_8 = new javax.swing.JLabel();
        label8_8 = new javax.swing.JLabel();
        label6_6 = new javax.swing.JLabel();
        label7_6 = new javax.swing.JLabel();
        label8_6 = new javax.swing.JLabel();
        label6_7 = new javax.swing.JLabel();
        label7_7 = new javax.swing.JLabel();
        label8_7 = new javax.swing.JLabel();
        label6_8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton2.setText("New Board");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        label0_0.setText("0_0");

        label1_0.setText("1_0");

        label2_0.setText("2_0");

        label0_1.setText("(0,0)");

        label1_1.setText("(0,0)");

        label2_1.setText("(0,0)");

        label0_2.setText("(0,0)");

        label1_2.setText("(0,0)");

        label2_2.setText("(0,0)");

        label4_2.setText("(0,0)");

        label5_2.setText("(0,0)");

        label3_0.setText("3_0");

        label4_0.setText("4_0");

        label5_0.setText("5_0");

        label3_1.setText("(0,0)");

        label4_1.setText("(0,0)");

        label5_1.setText("(0,0)");

        label3_2.setText("(0,0)");

        label7_2.setText("(0,0)");

        label8_2.setText("(0,0)");

        label6_0.setText("(0,0)");

        label7_0.setText("(0,0)");

        label8_0.setText("(0,0)");

        label6_1.setText("(0,0)");

        label7_1.setText("(0,0)");

        label8_1.setText("(0,0)");

        label6_2.setText("(0,0)");

        label0_3.setText("(0,0)");

        label1_3.setText("(0,0)");

        label2_3.setText("(0,0)");

        label0_4.setText("(0,0)");

        label1_4.setText("(0,0)");

        label2_4.setText("(0,0)");

        label0_5.setText("(0,0)");

        label1_5.setText("(0,0)");

        label2_5.setText("(0,0)");

        label4_5.setText("(0,0)");

        label5_5.setText("(0,0)");

        label3_3.setText("(0,0)");

        label4_3.setText("(0,0)");

        label5_3.setText("(0,0)");

        label3_4.setText("(0,0)");

        label4_4.setText("(0,0)");

        label5_4.setText("(0,0)");

        label3_5.setText("(0,0)");

        label7_5.setText("(0,0)");

        label8_5.setText("(0,0)");

        label6_3.setText("(0,0)");

        label7_3.setText("(0,0)");

        label8_3.setText("(0,0)");

        label6_4.setText("(0,0)");

        label7_4.setText("(0,0)");

        label8_4.setText("(0,0)");

        label6_5.setText("(0,0)");

        label0_6.setText("(0,0)");

        label1_6.setText("(0,0)");

        label2_6.setText("(0,0)");

        label0_7.setText("(0,0)");

        label1_7.setText("(0,0)");

        label2_7.setText("(0,0)");

        label0_8.setText("(0,0)");

        label1_8.setText("(0,0)");

        label2_8.setText("(0,0)");

        label4_8.setText("(0,0)");

        label5_8.setText("(0,0)");

        label3_6.setText("(0,0)");

        label4_6.setText("(0,0)");

        label5_6.setText("(0,0)");

        label3_7.setText("(0,0)");

        label4_7.setText("(0,0)");

        label5_7.setText("(0,0)");

        label3_8.setText("(0,0)");

        label7_8.setText("(0,0)");

        label8_8.setText("(0,0)");

        label6_6.setText("(0,0)");

        label7_6.setText("(0,0)");

        label8_6.setText("(0,0)");

        label6_7.setText("(0,0)");

        label7_7.setText("(0,0)");

        label8_7.setText("(0,0)");

        label6_8.setText("(0,0)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label0_4)
                            .addComponent(label0_3)
                            .addComponent(label0_5))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label1_4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label2_4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label1_5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label2_5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label1_3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label2_3))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label0_7)
                            .addComponent(label0_6)
                            .addComponent(label0_8))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label1_7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label2_7))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label1_8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label2_8))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label1_6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label2_6))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(label0_1)
                                    .addComponent(label0_2))
                                .addGap(14, 14, 14))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label0_0)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label1_1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label2_1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label1_2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label2_2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label1_0)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label2_0)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label3_2)
                                .addGap(14, 14, 14)
                                .addComponent(label4_2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label5_2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(label3_1)
                                    .addComponent(label3_0, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(label4_0)
                                    .addComponent(label4_1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label5_1)
                                    .addComponent(label5_0))))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label6_1)
                            .addComponent(label6_0)
                            .addComponent(label6_2))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label7_1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label8_1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label7_2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label8_2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label7_0)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label8_0))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label3_4)
                            .addComponent(label3_3)
                            .addComponent(label3_5))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label4_4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label5_4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label4_5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label5_5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label4_3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label5_3)))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label6_4)
                            .addComponent(label6_3)
                            .addComponent(label6_5))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label7_4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label8_4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label7_5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label8_5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label7_3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label8_3))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label3_7)
                            .addComponent(label3_6)
                            .addComponent(label3_8))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label4_7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label5_7))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label4_8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label5_8))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label4_6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label5_6)))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label6_7)
                            .addComponent(label6_6)
                            .addComponent(label6_8))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label7_7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label8_7))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label7_8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label8_8))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label7_6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label8_6)))))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(label6_0)
                                    .addComponent(label7_0)
                                    .addComponent(label8_0))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(label6_1)
                                    .addComponent(label7_1)
                                    .addComponent(label8_1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(label6_2)
                                    .addComponent(label7_2)
                                    .addComponent(label8_2)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(label3_0)
                                    .addComponent(label4_0)
                                    .addComponent(label5_0))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(label3_1)
                                    .addComponent(label4_1)
                                    .addComponent(label5_1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(label3_2)
                                    .addComponent(label4_2)
                                    .addComponent(label5_2)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label0_0)
                            .addComponent(label1_0)
                            .addComponent(label2_0))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label0_1)
                            .addComponent(label1_1)
                            .addComponent(label2_1))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label0_2)
                            .addComponent(label1_2)
                            .addComponent(label2_2))))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(label6_3)
                                .addComponent(label7_3)
                                .addComponent(label8_3))
                            .addGap(10, 10, 10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(label6_4)
                                .addComponent(label7_4)
                                .addComponent(label8_4))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(label6_5)
                                .addComponent(label7_5)
                                .addComponent(label8_5)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(label3_3)
                                .addComponent(label4_3)
                                .addComponent(label5_3))
                            .addGap(10, 10, 10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(label3_4)
                                .addComponent(label4_4)
                                .addComponent(label5_4))
                            .addGap(12, 12, 12)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(label3_5)
                                .addComponent(label4_5)
                                .addComponent(label5_5))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label0_3)
                            .addComponent(label1_3)
                            .addComponent(label2_3))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label0_4)
                            .addComponent(label1_4)
                            .addComponent(label2_4))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label0_5)
                            .addComponent(label1_5)
                            .addComponent(label2_5))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(label6_6)
                                .addComponent(label7_6)
                                .addComponent(label8_6))
                            .addGap(10, 10, 10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(label6_7)
                                .addComponent(label7_7)
                                .addComponent(label8_7))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(label6_8)
                                .addComponent(label7_8)
                                .addComponent(label8_8)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(label3_6)
                                .addComponent(label4_6)
                                .addComponent(label5_6))
                            .addGap(10, 10, 10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(label3_7)
                                .addComponent(label4_7)
                                .addComponent(label5_7))
                            .addGap(12, 12, 12)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(label3_8)
                                .addComponent(label4_8)
                                .addComponent(label5_8))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label0_6)
                            .addComponent(label1_6)
                            .addComponent(label2_6))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label0_7)
                            .addComponent(label1_7)
                            .addComponent(label2_7))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label0_8)
                            .addComponent(label1_8)
                            .addComponent(label2_8))))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        GenerateRandom aBoard = new GenerateRandom();
        while (!aBoard.checkIfCompleted){ // while is here because GenerateRandom is brute force and doesnt always completes a board
            aBoard = new GenerateRandom();
        }
        String key = String.valueOf(aBoard.getKey(0, 0));
        label0_0.setText(key);
        key = String.valueOf(aBoard.getKey(1, 0));
        label1_0.setText(key);
        key = String.valueOf(aBoard.getKey(2, 0));
        label2_0.setText(key);
        key = String.valueOf(aBoard.getKey(3, 0));
        label3_0.setText(key);
        key = String.valueOf(aBoard.getKey(4, 0));
        label4_0.setText(key);
        key = String.valueOf(aBoard.getKey(5, 0));
        label5_0.setText(key);
        key = String.valueOf(aBoard.getKey(6, 0));
        label6_0.setText(key);
        key = String.valueOf(aBoard.getKey(7, 0));
        label7_0.setText(key);
        key = String.valueOf(aBoard.getKey(8, 0));
        label8_0.setText(key);
        key = String.valueOf(aBoard.getKey(0, 1));
        label0_1.setText(key);
        key = String.valueOf(aBoard.getKey(1, 1));
        label1_1.setText(key);
        key = String.valueOf(aBoard.getKey(2, 1));
        label2_1.setText(key);
        key = String.valueOf(aBoard.getKey(3, 1));
        label3_1.setText(key);
        key = String.valueOf(aBoard.getKey(4, 1));
        label4_1.setText(key);
        key = String.valueOf(aBoard.getKey(5, 1));
        label5_1.setText(key);
        key = String.valueOf(aBoard.getKey(6, 1));
        label6_1.setText(key);
        key = String.valueOf(aBoard.getKey(7, 1));
        label7_1.setText(key);
        key = String.valueOf(aBoard.getKey(8, 1));
        label8_1.setText(key);
        key = String.valueOf(aBoard.getKey(0, 2));
        label0_2.setText(key);
        key = String.valueOf(aBoard.getKey(1, 2));
        label1_2.setText(key);
        key = String.valueOf(aBoard.getKey(2, 2));
        label2_2.setText(key);
        key = String.valueOf(aBoard.getKey(3, 2));
        label3_2.setText(key);
        key = String.valueOf(aBoard.getKey(4, 2));
        label4_2.setText(key);
        key = String.valueOf(aBoard.getKey(5, 2));
        label5_2.setText(key);
        key = String.valueOf(aBoard.getKey(6, 2));
        label6_2.setText(key);
        key = String.valueOf(aBoard.getKey(7, 2));
        label7_2.setText(key);
        key = String.valueOf(aBoard.getKey(8, 2));
        label8_2.setText(key);
        key = String.valueOf(aBoard.getKey(0, 3));
        label0_3.setText(key);
        key = String.valueOf(aBoard.getKey(1, 3));
        label1_3.setText(key);
        key = String.valueOf(aBoard.getKey(2, 3));
        label2_3.setText(key);
        key = String.valueOf(aBoard.getKey(3, 3));
        label3_3.setText(key);
        key = String.valueOf(aBoard.getKey(4, 3));
        label4_3.setText(key);
        key = String.valueOf(aBoard.getKey(5, 3));
        label5_3.setText(key);
        key = String.valueOf(aBoard.getKey(6, 3));
        label6_3.setText(key);
        key = String.valueOf(aBoard.getKey(7, 3));
        label7_3.setText(key);
        key = String.valueOf(aBoard.getKey(8, 3));
        label8_3.setText(key);
        key = String.valueOf(aBoard.getKey(0, 4));
        label0_4.setText(key);
        key = String.valueOf(aBoard.getKey(1, 4));
        label1_4.setText(key);
        key = String.valueOf(aBoard.getKey(2, 4));
        label2_4.setText(key);
        key = String.valueOf(aBoard.getKey(3, 4));
        label3_4.setText(key);
        key = String.valueOf(aBoard.getKey(4, 4));
        label4_4.setText(key);
        key = String.valueOf(aBoard.getKey(5, 4));
        label5_4.setText(key);
        key = String.valueOf(aBoard.getKey(6, 4));
        label6_4.setText(key);
        key = String.valueOf(aBoard.getKey(7, 4));
        label7_4.setText(key);
        key = String.valueOf(aBoard.getKey(8, 4));
        label8_4.setText(key);
        key = String.valueOf(aBoard.getKey(0, 5));
        label0_5.setText(key);
        key = String.valueOf(aBoard.getKey(1, 5));
        label1_5.setText(key);
        key = String.valueOf(aBoard.getKey(2, 5));
        label2_5.setText(key);
        key = String.valueOf(aBoard.getKey(3, 5));
        label3_5.setText(key);
        key = String.valueOf(aBoard.getKey(4, 5));
        label4_5.setText(key);
        key = String.valueOf(aBoard.getKey(5, 5));
        label5_5.setText(key);
        key = String.valueOf(aBoard.getKey(6, 5));
        label6_5.setText(key);
        key = String.valueOf(aBoard.getKey(7, 5));
        label7_5.setText(key);
        key = String.valueOf(aBoard.getKey(8, 5));
        label8_5.setText(key);
        key = String.valueOf(aBoard.getKey(0, 6));
        label0_6.setText(key);
        key = String.valueOf(aBoard.getKey(1, 6));
        label1_6.setText(key);
        key = String.valueOf(aBoard.getKey(2, 6));
        label2_6.setText(key);
        key = String.valueOf(aBoard.getKey(3, 6));
        label3_6.setText(key);
        key = String.valueOf(aBoard.getKey(4, 6));
        label4_6.setText(key);
        key = String.valueOf(aBoard.getKey(5, 6));
        label5_6.setText(key);
        key = String.valueOf(aBoard.getKey(6, 6));
        label6_6.setText(key);
        key = String.valueOf(aBoard.getKey(7, 6));
        label7_6.setText(key);
        key = String.valueOf(aBoard.getKey(8, 6));
        label8_6.setText(key);
        key = String.valueOf(aBoard.getKey(0, 7));
        label0_7.setText(key);
        key = String.valueOf(aBoard.getKey(1, 7));
        label1_7.setText(key);
        key = String.valueOf(aBoard.getKey(2, 7));
        label2_7.setText(key);
        key = String.valueOf(aBoard.getKey(3, 7));
        label3_7.setText(key);
        key = String.valueOf(aBoard.getKey(4, 7));
        label4_7.setText(key);
        key = String.valueOf(aBoard.getKey(5, 7));
        label5_7.setText(key);
        key = String.valueOf(aBoard.getKey(6, 7));
        label6_7.setText(key);
        key = String.valueOf(aBoard.getKey(7, 7));
        label7_7.setText(key);
        key = String.valueOf(aBoard.getKey(8, 7));
        label8_7.setText(key);
        key = String.valueOf(aBoard.getKey(0, 8));
        label0_8.setText(key);
        key = String.valueOf(aBoard.getKey(1, 8));
        label1_8.setText(key);
        key = String.valueOf(aBoard.getKey(2, 8));
        label2_8.setText(key);
        key = String.valueOf(aBoard.getKey(3, 8));
        label3_8.setText(key);
        key = String.valueOf(aBoard.getKey(4, 8));
        label4_8.setText(key);
        key = String.valueOf(aBoard.getKey(5, 8));
        label5_8.setText(key);
        key = String.valueOf(aBoard.getKey(6, 8));
        label6_8.setText(key);
        key = String.valueOf(aBoard.getKey(7, 8));
        label7_8.setText(key);
        key = String.valueOf(aBoard.getKey(8, 8));
        label8_8.setText(key);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BoardGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BoardGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BoardGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BoardGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BoardGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel label0_0;
    private javax.swing.JLabel label0_1;
    private javax.swing.JLabel label0_2;
    private javax.swing.JLabel label0_3;
    private javax.swing.JLabel label0_4;
    private javax.swing.JLabel label0_5;
    private javax.swing.JLabel label0_6;
    private javax.swing.JLabel label0_7;
    private javax.swing.JLabel label0_8;
    private javax.swing.JLabel label1_0;
    private javax.swing.JLabel label1_1;
    private javax.swing.JLabel label1_2;
    private javax.swing.JLabel label1_3;
    private javax.swing.JLabel label1_4;
    private javax.swing.JLabel label1_5;
    private javax.swing.JLabel label1_6;
    private javax.swing.JLabel label1_7;
    private javax.swing.JLabel label1_8;
    private javax.swing.JLabel label2_0;
    private javax.swing.JLabel label2_1;
    private javax.swing.JLabel label2_2;
    private javax.swing.JLabel label2_3;
    private javax.swing.JLabel label2_4;
    private javax.swing.JLabel label2_5;
    private javax.swing.JLabel label2_6;
    private javax.swing.JLabel label2_7;
    private javax.swing.JLabel label2_8;
    private javax.swing.JLabel label3_0;
    private javax.swing.JLabel label3_1;
    private javax.swing.JLabel label3_2;
    private javax.swing.JLabel label3_3;
    private javax.swing.JLabel label3_4;
    private javax.swing.JLabel label3_5;
    private javax.swing.JLabel label3_6;
    private javax.swing.JLabel label3_7;
    private javax.swing.JLabel label3_8;
    private javax.swing.JLabel label4_0;
    private javax.swing.JLabel label4_1;
    private javax.swing.JLabel label4_2;
    private javax.swing.JLabel label4_3;
    private javax.swing.JLabel label4_4;
    private javax.swing.JLabel label4_5;
    private javax.swing.JLabel label4_6;
    private javax.swing.JLabel label4_7;
    private javax.swing.JLabel label4_8;
    private javax.swing.JLabel label5_0;
    private javax.swing.JLabel label5_1;
    private javax.swing.JLabel label5_2;
    private javax.swing.JLabel label5_3;
    private javax.swing.JLabel label5_4;
    private javax.swing.JLabel label5_5;
    private javax.swing.JLabel label5_6;
    private javax.swing.JLabel label5_7;
    private javax.swing.JLabel label5_8;
    private javax.swing.JLabel label6_0;
    private javax.swing.JLabel label6_1;
    private javax.swing.JLabel label6_2;
    private javax.swing.JLabel label6_3;
    private javax.swing.JLabel label6_4;
    private javax.swing.JLabel label6_5;
    private javax.swing.JLabel label6_6;
    private javax.swing.JLabel label6_7;
    private javax.swing.JLabel label6_8;
    private javax.swing.JLabel label7_0;
    private javax.swing.JLabel label7_1;
    private javax.swing.JLabel label7_2;
    private javax.swing.JLabel label7_3;
    private javax.swing.JLabel label7_4;
    private javax.swing.JLabel label7_5;
    private javax.swing.JLabel label7_6;
    private javax.swing.JLabel label7_7;
    private javax.swing.JLabel label7_8;
    private javax.swing.JLabel label8_0;
    private javax.swing.JLabel label8_1;
    private javax.swing.JLabel label8_2;
    private javax.swing.JLabel label8_3;
    private javax.swing.JLabel label8_4;
    private javax.swing.JLabel label8_5;
    private javax.swing.JLabel label8_6;
    private javax.swing.JLabel label8_7;
    private javax.swing.JLabel label8_8;
    // End of variables declaration//GEN-END:variables
}
